name: CI

on:
  pull_request:
  push:
    branches: [main]
    tags: ["v*.*.*"] # tagging triggers build/publish path
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12", "3.13"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install deps
        run: uv sync --dev
      - name: Run tests
        run: uv run -m pytest -q

  build:
    runs-on: ubuntu-latest
    needs: tests
    if: startsWith(github.ref, 'refs/tags/') # only on tag pushes
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version: "3.10"
      - name: Build dist
        run: uv build
      - name: Check dist
        run: uvx twine check dist/*

  publish:
    runs-on: ubuntu-latest
    needs: build
    if: needs.build.result == 'success'
    permissions:
      contents: read
      id-token: write
    environment: pypi
    steps:
      - uses: actions/checkout@v4
      - name: Publish to PyPI (OIDC)
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          skip-existing: true
          verbose: true
          attestations: true
          password: ${{ secrets.PYPI_API_TOKEN }}
